/**
 * The Render Engine
 * Touch
 *
 * Copyright (c) 2011 Brett Fattori (brettf@renderengine.com)
 */
"use strict";

/**
 * @class A data object which represents a touch event generated by {@link TouchComponent}.
 *        Since touches are handled differently across platforms, this class aims to
 *        normalize what is returned and allow a game to handle the input without concern
 *        for platform.
 *
 * @param touch {Event} The touch from the event object
 * @constructor
 * @description A touch data object.
 */
class Touch {

    constructor(touch) {
        this._touch = touch;
    }

    /**
     * Get the class name of this object
     *
     * @return {String} "R.struct.Touch"
     */
    static get className() {
        return "Touch";
    }

    /**
     * Get the X coordinate of the touch
     */
    getX() {
        return this._touch.pageX;
    }

    /**
     * Get the Y coordinate of the touch
     */
    getY() {
        return this._touch.pageY;
    }

    get x() {
        return this._touch.pageX;
    }

    get y() {
        return this._touch.pageY;
    }

    /**
     * Get a {@link Point2D} which represents the location of the touch
     */
    get() {
        return Point2D.create(this.x, this.y);
    }

}
